#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: freezer-agent | install | Update venv cache
  become: yes
  install_package:
    cache: update

- name: freezer-agent | install | Install Freezer_agent virtual env
  become: yes
  install_package:
    name: freezer_agent
    service: freezer-agent
    state: present
    activate: act_off
  register: freezer_agent_install_result

- name: freezer-agent | install | Register freezer-scheduler with systemd
  become: yes
  setup_systemd:
    name: freezer-scheduler
    service: freezer-agent
    cmd: freezer-scheduler
    restart: on-failure
    user: root
    group: root
    args: "start --config-file {{ freezer_agent_conf_dir }}/scheduler.conf "

- name: freezer-agent | install | Set service directories
  set_fact:
    freezer_agent_conf_dir: "{{ 'freezer-agent' |  config_dir(freezer_agent_install_result.version) }}"
    freezer_agent_bin_dir: "{{ 'freezer-agent' |  bin_dir(freezer_agent_install_result.version) }}"

- name: freezer-agent | install | Check if Freezer agent is available
  become: yes
  stat:
    path: "{{ freezer_agent_bin_dir }}/freezerc"
  register: freezer_agent_bin_result

- name: freezer-agent | install | Check if Freezer scheduler is available
  become: yes
  stat:
    path: "{{ freezer_agent_bin_dir }}/freezer-scheduler"
  register: freezer_scheduler_bin_result

- name: freezer-agent | install | Enabling freezer agent for all users
  become: yes
  file:
    src: "{{ freezer_agent_bin_dir }}/freezerc"
    dest: /usr/bin/freezer-agent
    state: link
    force: yes
  when: freezer_agent_bin_result.stat.exists and freezer_agent_bin_result.stat.xusr

- name: freezer-agent | install | Enabling freezer scheduler for all users
  become: yes
  file:
    src: "{{ freezer_agent_bin_dir }}/freezer-scheduler"
    dest: /usr/bin/freezer-scheduler
    state: link
    force: yes
  when: freezer_scheduler_bin_result.stat.exists and freezer_scheduler_bin_result.stat.xusr

- name: freezer-client | install | Check if Freezer client is available
  become: yes
  stat:
    path: "{{ freezer_agent_bin_dir }}/freezer"
  register: freezer_client_bin_result

- name: freezer-client | install | Enabling freezer client for all users
  become: yes
  file:
    src: "{{ freezer_agent_bin_dir }}/freezer"
    dest: /usr/bin/freezer
    state: link
    force: yes
  when: freezer_client_bin_result.stat.exists and freezer_client_bin_result.stat.xusr
